function cat_help()
%CAT_HELP Info about Channel Analysis Toolbox usage
%
% Add the "Channel Analysis Toolbox" to the path, with subfolders.
%	This toolbox uses the following toolboxes, add these to your path, run them and save your path:
%	- Generic Function Toolbox
%	- EEGLab
%	- SPM12
%
% All methods and functions in this toolbox expect a struct with at least the
% following starting fields:
%   group       group name (required for some functions, can be added anytime)
%   paradigm    paradigm name, such as 'Rest', 'P300', 'N-Back'
%   event       event name, such as 'EyesClosed', 'Target', 'Standard'
%   fs          sampling frequency
%   channels    substruct containing
%     labels    cell array of channel labels
%     positions	2D matrix of 2D positions of all electrodes
%   filenames   cell array of original relative file names
%   timeseries  substruct containing
%     epochs    4D matrix with dimensions "time", "locations", "epochs", "subjects"
%     average   3D matrix with dimensions "time", "locations", "subjects"
%     times     vector containing timestamps within an epoch
%
% The struct described above contains ALL data from several files of one subject
% group, for one paradigm, for one event type. Such a struct can be generated by
% using cat_eeg_loadfolder to load a folder containing set files produced by EEGLab.
%
% This toolbox contains methods in different categories:
%   edge  	edge detection methods and methods to select different bands in the results
%   load  	CAT struct loading and saving, or loading initial CAT struct from EEGlab files
%   misc  	convenience functions
%   plot  	plotting functions for different analysis results
%   proc    conversion and processing methods for EEGlab file formats
%   spect 	spectral analysis methods
%   time  	time analysis methods
%
% Bugs in EEGlab and its plugins (see the readme for the solutions)
%   Converting SPM to EEGlab
%   Installing SASICA

% Last edit: 20200129 Jorne Laton - Updated according to latest changes
% Authors:   Jorne Laton

help cat_help

end