function cat_help()
%CAT_HELP Info about Channel Analysis Toolbox usage
%
% Add the "Channel Analysis Toolbox" to the path, with subfolders.
%	This toolbox uses the following toolboxes, add these to your path as well:
%	- Generic Function Toolbox
%	- EEGLab
%	- SPM12
%
% All methods and functions in this toolbox expect a struct with at least the
% following starting fields:
%   fs          sampling frequency
%   timeseries  substruct containing
%     epochs    4D matrix with dimensions "time", "locations", "epochs", "subjects"
%     average   3D matrix with dimensions "time", "locations", "subjects"
%     times     vector containing timestamps within an epoch
%   channels    substruct containing
%     labels    cell array of channel labels
%     positions	2D matrix of 2D positions of all electrodes
%   filenames   cell array of original relative file names
%   group       group name (required for some functions, can be added anytime)
%   paradigm    paradigm name, such as 'Rest', 'P300', 'N-Back'
%   event       event name, such as 'EyesClosed', 'Target', 'Standard'
%
% The struct described above contains ALL data from several files of one subject
% group, for one paradigm, for one event type. Such a struct can be generated by
% using eat_set_loadfolder to load a folder containing set files produced by EEGLab.
%
% This toolbox contains methods in different categories:
%   conv  	functions to convert files to set files
%   edge  	edge detection methods and methods to select different bands in the
%         	results
%   spect 	spectral analysis methods
%   load  	external format loading methods, for instance eeglab's set files into
%         	starting struct
%   misc  	several convenience methods
%   plot  	plotting functions for different analysis results
%   preproc	preprocessing methods for EEGlab file formats
%   time  	time analysis methods

% #2019.12.10 Jorne Laton#

help cat_help

end