function cm = blackcentered(lowcolor, highcolor, m)
highpart = [linspace(highcolor(1), 0, floor((m+1)/2)); ...
           linspace(highcolor(2), 0, floor((m+1)/2)); ...
           linspace(highcolor(3), 0, floor((m+1)/2))];
         
lowpart = [linspace(0, lowcolor(1), ceil((m+1)/2)); ...
            linspace(0, lowcolor(2), ceil((m+1)/2)); ...
            linspace(0, lowcolor(3), ceil((m+1)/2))];
         
cm = [highpart lowpart(:, 2:end)]';